Repository michal-bootcamp/WDP-1904-01, pull requests merged in 2019-04, with the labels that each got.

#27 Wdp190401 34 Usunięcie białej linii z ikony koszyka
  src/partials/70_section-blog-posts.html
  src/sass/components/_header.scss
  src/sass/components/_post-box.scss
Labels: ready to merge

#10 WDP190401-10
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: ready to merge

#13 WDP190401 17
  src/partials/50_section-products.html
  src/sass/components/_panel-bar.scss
Labels: ready to merge

#18 WDP190401-24 / WDP190401-25
  .gitignore
  src/images/sale/sale-image1.jpg
  src/images/sale/sale-image2.png
  src/images/sale/sale-image3.png
  src/images/sale/sale-image4.png
  src/index.html
  src/partials/40_section-sale.html
  src/sass/_placeholders.scss
  src/sass/_variables.scss
  src/sass/components/_section--sale.scss
  src/sass/style.scss
Labels: ready to merge

#30 Wdp190401 36 readme.md update
  README.md
Labels: for deploy

#25 WDP190401-29/30/31
  src/images/brands/Layer_138.png
  src/images/brands/Layer_139.png
  src/images/brands/Layer_140.png
  src/images/brands/Layer_141.png
  src/images/brands/Layer_142.png
  src/index.html
  src/partials/50_section-products.html
  src/partials/80_section-brands.html
  src/sass/components/_brands-slider.scss
  src/sass/components/_panel-bar.scss
  src/sass/style.scss
  src/scripts/app.js
Labels: needs work
