Repository michal-bootcamp/WDP-1904-01, pull requests merged in 2019-05, with the labels that each got.

#9 WDP190401-11
  src/images/beds/Thumbs.db
  src/images/blog/Thumbs.db
  src/partials/10_header.html
  src/sass/_placeholders.scss
  src/sass/components/_header.scss
  src/scripts/app.js
Labels: ready to merge

#19 WDP190401-26
  src/images/gallery/bed.png
  src/images/gallery/chair-1.png
  src/images/gallery/chair-2.png
  src/images/gallery/chair-3.png
  src/images/gallery/chair-4.png
  src/index.html
  src/partials/50_section-products.html
  src/partials/60_section-gallery.html
  src/sass/_variables.scss
  src/sass/components/_button.scss
  src/sass/components/_feature-box.scss
  src/sass/components/_product-box.scss
  src/sass/components/_section--gallery.scss
  src/sass/style.scss
  src/scripts/app.js
Labels: ready to merge

#17 WDP190401-19
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
  src/scripts/app.js
Labels: needs work

#20 WDP190401-21 / WDP190401-22 / WDP190401-23
  FETCH_HEAD
  src/images/featured/featured-1.jpeg
  src/images/featured/featured-2.jpeg
  src/index.html
  src/partials/20_section-featured.html
  src/sass/_placeholders.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_product-box-featured.scss
  src/sass/components/_product-box.scss
  src/sass/components/_section--features.scss
  src/sass/components/_slider-featured.scss
  src/sass/style.scss
Labels: needs work

#24 WDP190401-27
  package-lock.json
  package.json
  src/images/gallery/bed.png
  src/images/gallery/chair-1.png
  src/images/gallery/chair-10.png
  src/images/gallery/chair-11.png
  src/images/gallery/chair-12.png
  src/images/gallery/chair-2.png
  src/images/gallery/chair-3.png
  src/images/gallery/chair-4.png
  src/images/gallery/chair-5.png
  src/images/gallery/chair-6.png
  src/images/gallery/chair-7.png
  src/images/gallery/chair-8.png
  src/images/gallery/chair-9.png
  src/images/gallery/sofa-1.png
  src/images/gallery/sofa-2.png
  src/images/gallery/sofa-3.png
  src/images/gallery/sofa-4.png
  src/images/gallery/table-1.png
  src/index.html
  src/partials/60_section-gallery.html
  src/sass/components/_section--gallery.scss
  src/scripts/app.js
Labels: for deploy

#29 WDP190401-28
  src/sass/components/_section--gallery.scss
  src/scripts/app.js
Labels: ready to merge
